### ISSUE TITLE
F12 bug 撲滅

### ISSUE THREAD

**Issue by u-ecmaker** [ECMaker/blog#77]
![image](https://github.com/ECMaker/blog/assets/97171717/4fb0e49e-b456-4eff-841c-a263d7ae1e78)
```
framework-2c79e2a64abdb08b.js:9 Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at rh (framework-2c79e2a64abdb08b.js:9:40169)
    at framework-2c79e2a64abdb08b.js:9:103474
    at oD (framework-2c79e2a64abdb08b.js:9:106224)
    at oO (framework-2c79e2a64abdb08b.js:9:99172)
    at framework-2c79e2a64abdb08b.js:9:98979
    at oF (framework-2c79e2a64abdb08b.js:9:98986)
    at oS (framework-2c79e2a64abdb08b.js:9:94025)
    at x (framework-2c79e2a64abdb08b.js:33:1373)
    at MessagePort.T (framework-2c79e2a64abdb08b.js:33:1903)
3
framework-2c79e2a64abdb08b.js:9 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lh (framework-2c79e2a64abdb08b.js:9:46422)
    at i (framework-2c79e2a64abdb08b.js:9:121159)
    at oO (framework-2c79e2a64abdb08b.js:9:99112)
    at framework-2c79e2a64abdb08b.js:9:98979
    at oF (framework-2c79e2a64abdb08b.js:9:98986)
    at oS (framework-2c79e2a64abdb08b.js:9:94025)
    at x (framework-2c79e2a64abdb08b.js:33:1373)
    at MessagePort.T (framework-2c79e2a64abdb08b.js:33:1903)
framework-2c79e2a64abdb08b.js:9 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (framework-2c79e2a64abdb08b.js:9:120828)
    at oO (framework-2c79e2a64abdb08b.js:9:99112)
    at framework-2c79e2a64abdb08b.js:9:98979
    at oF (framework-2c79e2a64abdb08b.js:9:98986)
    at ox (framework-2c79e2a64abdb08b.js:9:95738)
    at oS (framework-2c79e2a64abdb08b.js:9:94293)
    at x (framework-2c79e2a64abdb08b.js:33:1373)
    at MessagePort.T (framework-2c79e2a64abdb08b.js:33:1903)
blog.ec-maker.com/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
﻿```

**Comment by u-ecmaker** [comment]
chat GPT 4o を使ったら一瞬で解決した。
3.5とは偉い違いだ。2-3段階進んだ気がする。

**Comment by u-ecmaker** [comment]
## ToDo
![image](https://github.com/user-attachments/assets/c60bf69b-0587-412c-b0a0-1efed012b9f9)

**Comment by u-ecmaker** [comment]
これか？
![image](https://github.com/user-attachments/assets/1bb3ba69-1457-46a4-a18b-bf01901f8caa)

**Comment by u-ecmaker** [comment]
### ~~((PR1 (old))) 中止 PR #79 を参照。branch削除。~~
### PR2 #80 → やめた。
一旦、noblog様の最新 11sep2023 main を持ってきて、エラーシュート。
### ~~PR3-4 git操作ミス deleted.~~
### PR5 方針転換→基本的にはこれでクリア
最新のnoblog様は持ってこずに、過去のnoblog様ベースのそのままエラーシュート。 

### PR6 本PR。残り。
まだ一つだけ消えないので、考えられる処置を講じてみる

---

#updated
actions, next config update

**Comment by u-ecmaker** [comment]
slugの404は解決。 #89 が原因。

## ToDo
残るエラーの出るブロックへの対処
![image](https://github.com/user-attachments/assets/6ae4ba8a-9f75-46d2-b8a8-105399587b21)

**Comment by u-ecmaker** [comment]
## 残るエラーの出るブロックへの対処
![image](https://github.com/user-attachments/assets/c0601f5d-3c39-4793-b362-8e646098efe7)

### Youtubeは解決  
残りはadBlockによるものだと分かった。シークレットモードではerrorにならない。
![image](https://github.com/user-attachments/assets/56ec2440-9d7f-41af-91a2-1cbf07d384bb)

### すべてのブロックの確認  
切り出した→ #90  

## TIkTokの埋め込みはエラーが残ったが解なしとして残置する。

本家Notionの埋め込みでもエラーとなるのでしょうがない。
おそらく提供されているembedコードに間違いがある。

対策のしようが無いのでクローズ。  
![image](https://github.com/user-attachments/assets/86e34b1d-0c9d-42a6-8b58-fbd6eae616df)

### すべてのブロックで確認
previewページを参照してみた。→ #90  
https://blog.ec-maker.com/posts/Notion-Block-Preview  
![image](https://github.com/user-attachments/assets/6bf86fa4-3326-4b2a-93f4-6a88adc0a808)
